name: redis-deployment

releases:
- name: redis
  version: create
  url: file://.

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: redis-server
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: redis
    release: redis
    properties:
      port: 6380
      username: admin
      password: password
    templates:
    - name: redis
      release: redis
